# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36696f77736080f4ac2b01d71217da55efab3d8a81d900afe3e0987a293e29c83670324f93e6c068d4dbbfd4adffd77c4bbda8f93768c3e383c233d530529cfa

test:
  secret_key_base: b87feb5592c218d2c60cdd1de7cad505de1905b1592e3ca01af3a4f5a72bafb3d67acc3a32a5e0f1e86495bc0abc93e581aa52a8115d594f46693d656d028f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
